# Generated by Django 5.2.3 on 2026-06-22 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='monthly_saving',
            field=models.PositiveIntegerField(default=400000),
        ),
    ]
