# Generated by Django 5.2.15 on 2026-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_monthly_saving'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age_group',
            field=models.CharField(blank=True, choices=[('', '선택 안 함'), ('child', '어린이'), ('youth', '청년'), ('middle', '중장년'), ('senior', '시니어')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='asset_level',
            field=models.CharField(blank=True, choices=[('', '선택 안 함'), ('low', '적음'), ('middle', '보통'), ('high', '많음')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('', '선택 안 함'), ('student', '학생'), ('employee', '직장인'), ('self_employed', '자영업자'), ('retired', '은퇴/퇴직')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='has_children',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='income_level',
            field=models.CharField(blank=True, choices=[('', '선택 안 함'), ('low', '낮음'), ('middle', '보통'), ('high', '높음')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', '선택 안 함'), ('single', '미혼'), ('married', '기혼')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='saving_purpose',
            field=models.CharField(blank=True, choices=[('', '선택 안 함'), ('emergency', '비상금'), ('housing', '주거/내 집 마련'), ('education', '교육/자녀'), ('retirement', '노후 준비'), ('travel', '여행/목돈')], default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='risk_tolerance',
            field=models.CharField(blank=True, choices=[('stable', '안정형'), ('balanced', '균형형'), ('aggressive', '수익형')], default='stable', max_length=20),
        ),
    ]
