# Generated by Django 5.2.15 on 2026-06-25 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_profile_image'),
        ('core', '0005_favoritesavings'),
    ]

    operations = [
    ]
